services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      # フロントエンドのソースコードをコンテナ内の/appディレクトリにマウント
      - ./backend:/app
      # node_modulesディレクトリをコンテナ内の/app/node_modulesに保持
      - /app/node_modules
